# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name CI
on: [push, pull_request]

jobs:
  flutter:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ui_flutter

    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze code
        run: flutter analyze

      - name: Run tests
        run: flutter test --no-pub

      - name: Run integration tests
        run: flutter test integration_test/ --no-pub

      - name: Install Linux build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev

      - name: Build Linux bundle
        run: flutter build linux --release

      - name: Upload Linux bundle
        uses: actions/upload-artifact@v4
        with:
          name: lorien-linux-bundle
          path: build/linux/x64/release/bundle

  # Optional: API tests if monorepo includes API
  api:
    if: hashFiles('api/**') != ''
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: pytest -q
