# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Flutter CI

on:
  push:
    branches: [ ui/phase6-core, main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      
      - run: flutter pub get
      
      - run: flutter analyze
      
      - run: flutter test --no-pub
