# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Flutter CI

on:
  push:
    branches: [ ui/phase6-core, main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      
      - run: flutter pub get
      
      - run: flutter analyze
      
      - name: Run tests with coverage
        run: flutter test --coverage --reporter expanded
      
      - name: Enforce coverage >= 20%
        run: |
          LCOV=$(grep -Po 'LF:\K\d+' coverage/lcov.info | awk '{sum+=$1} END {print sum}')
          HCOV=$(grep -Po 'LH:\K\d+' coverage/lcov.info | awk '{sum+=$1} END {print sum}')
          PCT=$((100*HCOV/LCOV))
          echo "Coverage: $PCT%"
          if [ "$PCT" -lt "20" ]; then echo "Coverage gate failed"; exit 1; fi
