site_name: Lorien
nav:
  - Home: README.md
  - Overview: docs/ProjectOverview.md
  - Design Decisions: docs/DesignDecisions.md
  - API: docs/API.md
  - Schema: docs/Schema.md
  - Backup & Restore: docs/Backup_Restore.md
  - LLM: docs/LLM_README.md
  - Safety: docs/Medical_Safety.md
  - Dev Quickstart: docs/Dev_Quickstart.md
  - WSL: docs/Setup_WSL.md
  - Release Notes: docs/ReleaseNotes_v6.7.md
theme:
  name: material
markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
