name: lorien
description: "Cross-platform decision tree management with AI-powered insights"
publish_to: 'none'
version: 0.6.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^5.6.0
  flutter_dotenv: ^5.1.0
  provider: ^6.1.1
  path_provider: ^2.1.1
  share_plus: ^10.0.2
  http: ^1.1.0
  flutter_riverpod: ^2.5.1
  pretty_dio_logger: ^1.3.1
  shared_preferences: ^2.3.2
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  go_router: ^14.1.0
  file_picker: ^8.1.2
  open_filex: ^4.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mocktail: ^1.0.3
  build_runner: ^2.4.10
  freezed: ^2.5.7
  json_serializable: ^6.9.0
  golden_toolkit: ^0.15.0

flutter:
  uses-material-design: true
