name: lorien
description: "Cross-platform decision tree management with AI-powered insights"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^5.5.0
  flutter_dotenv: ^5.1.0
  provider: ^6.1.1
  path_provider: ^2.1.1
  share_plus: ^7.2.1
  http: ^1.1.0
  flutter_riverpod: ^2.4.9
  pretty_dio_logger: ^1.3.1
  shared_preferences: ^2.2.2
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.11
  freezed: ^2.4.6
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
